---
version: 3

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '--force --verbose'

dependencies:
  ansible_core:
    package_pip: ansible-core==2.13.10
  ansible_runner:
    package_pip: ansible-runner==2.3.2
  galaxy: requirements.yml
